version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: sprintboard_db
    environment:
      POSTGRES_USER: Uncharted4
      POSTGRES_PASSWORD: Uncharted4
      POSTGRES_DB: sprintboard
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sprintboard_network

volumes:
  postgres_data:

networks:
  sprintboard_network:
    driver: bridge